name: Build LaTeX document

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: thesis/latex/thesis.tex
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: thesis.pdf      
      - run: ls -al
      - run: ls -al thesis/latex
      - name: Deploy report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          exclude_assets: '.github,agreements,examples,meetings,notes,presentations,prototype,report,thesis/,.gitignore,.gitmodules,README.md,thesis.acn,thesis.aux,thesis.bbl,thesis.bcf,thesis.blg,thesis.fdb_latexmk,thesis.fls,thesis.glo,thesis.ist,thesis.log,thesis.out,thesis.run.xml,thesis.toc'
          publish_dir: ./
