name: Build LaTeX document

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: thesis/latex/thesis.tex
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: thesis.pdf
      - name: Commit report
        run: |
          git config --global user.name 'Jan Schill'
          git config --global user.email 'janschill@users.noreply.github.com'
          git commit -am "Automated report"
          git push origin gh-pages
